# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Deepspace
on:
  push: 
   branches: main 

env:
  AZURE_WEBAPP_NAME: deepspacetest
  AZURE_WEBAPP_PACKAGE_PATH: ${{ github.workspace }}
  AZURE_WEBAPP_PUBLISH_PROFILE: ${{ secrets.AZURE_WEBAPP_PUBLISH_PROFILE }}

jobs:
 build:
    name: build
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v2
    
    - name: Azure login
      uses: azure/login@v1
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}
    
    - name: Set up JDK 1.9
      uses: actions/setup-java@v1
      with:
        java-version: 1.9
    
    - name: Build with Maven
      run: mvn -B package --file pom.xml
      

    - name: App Service Deploy
      uses: Azure/webapps-deploy@v2
      with:
       app-name: ${{ env.AZURE_WEBAPP_NAME }}
       package: ${{ env.AZURE_WEBAPP_PACKAGE_PATH }}/target/*.war
